[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
ast = true
ffi = true
build_info = true
extra_output = ["storageLayout"]
via_ir = true
libs = ["lib"]
allow_paths = [
  "node_modules",
]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
