[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
via_ir = true
libs = ["lib"]
allow_paths = [
  "node_modules",
]
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
